# Settings for GitHub repository
repository:
  # Automatically assign PRs to the author
  has_issues: true
  has_projects: false
  has_wiki: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  
  # Default branch protection
  branches:
    - name: main
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
        required_status_checks:
          strict: true
        enforce_admins: true
        restrictions: null

# Issue and PR templates
github:
  # Default labels for PRs
  labels:
    - name: bug
      color: d73a4a
      description: Something isn't working
    - name: enhancement
      color: a2eeef
      description: New feature or request
    - name: documentation
      color: 0075ca
      description: Documentation improvements
    - name: refactor
      color: 7057ff
      description: Code refactoring
    - name: needs-triage
      color: f9d0c4
      description: Needs initial review

  # Default assignees (GitHub usernames)
  collaborators:
    - username: david-slimp
      permission: admin
